### ISSUE TITLE
Should throw error if the given string is not even a timestring

### ISSUE THREAD

**Issue by garrychnca** [mike182uk/timestring#40]
I observe that there is already a test case for timestring having unrecognized time unit at: https://github.com/mike182uk/timestring/blob/f7366f6dfa62aa8cd91ddf8369d83177ec00ac3d/test.js#L88

However, the lib should do the same if the entire given string is not a timestring at all.

For now (release 5.0.0):

- timestring('test', 'milliseconds') => 0
- timestring('0test', 'milliseconds') => Error: The unit [test] is not supported by timestring

**Comment by garrychnca** [comment]
In addition, it will be great if a method can be exposed to check the validity of a timestring.

**Comment by prolink007** [comment]
I am also seeking this functionality.

**Comment by prolink007** [comment]
#43 I just submitted a PR to add in this error checking. Let me know if this is what you are desiring too, @garrychnca

**Comment by mike182uk** [comment]
Published #43 in `6.0.0`
